name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.3.0
  - hydra-core=1.0.6
  - numpy=1.23
  - pip:
      - wandb==0.16.4
      - hydra-joblib-launcher==1.1.2
      - protobuf==3.20.0
      - databricks-cli==0.17.6
